// File generated by Firebase CLI
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb, defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    return android;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALi974bDUOyTYeJsHfLQc8EgI30GWDibU',
    appId: '1:742259280712:web:d49ef383349cc039d7c17d',
    messagingSenderId: '742259280712',
    projectId: 'kurye-1db2f',
    authDomain: 'kurye-1db2f.firebaseapp.com',
    storageBucket: 'kurye-1db2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALi974bDUOyTYeJsHfLQc8EgI30GWDibU',
    appId: '1:742259280712:android:d49ef383349cc039d7c17d',
    messagingSenderId: '742259280712',
    projectId: 'kurye-1db2f',
    storageBucket: 'kurye-1db2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl42lyKDtQgFRElMatjP4mC7yJSFrXEGo',
    appId: '1:742259280712:ios:d5aeaef4d417ff6dd7c17d',
    messagingSenderId: '742259280712',
    projectId: 'kurye-1db2f',
    storageBucket: 'kurye-1db2f.firebasestorage.app',
    iosClientId:
        '742259280712-f8394boj5f91gkf49s3orgedir7hlvb4.apps.googleusercontent.com',
    iosBundleId: 'BG',
  );
}
